### ISSUE TITLE
Receive - consumer.MaximumWaitTime vs options.MaximumWaitTimeInMinutes

### ISSUE THREAD

**Issue by jefim** [FrendsPlatform/Frends.AzureEventHub#6]
- Both parameters need to be in seconds (currently one is in seconds, other is in minutes)
- consumer.MaximumWaitTime - if set to 0 then it should set the client to wait indefinitely
- Better docs for consumer.MaximumWaitTime - it should be clear what this controls vs the other parameter (emitting of empty event vs listening time overall)
- What happens when consumer.MaximumWaitTime triggers before options.MaximumWaitTimeInMinutes?

**Comment by ttossavainen** [comment]
merged
